### ISSUE TITLE
Vertical title offset wrong

### ISSUE THREAD

**Issue by hhanesand** [abellono/NavigationBarSelectorPageViewController#8]
![skjermbilde 2015-08-10 kl 20 10 08](https://cloud.githubusercontent.com/assets/1769314/9179294/dbbd5acc-3f9b-11e5-9969-88f427a0d5c9.png)

move down

**Comment by heumn** [comment]
![Alt Text](https://media3.giphy.com/media/tvHbsAxQnA4EM/200.gif)

**Comment by hhanesand** [comment]
doesn't seem to be wrong while running in demo app...

**Comment by heumn** [comment]
did you measure? :)

**Comment by hhanesand** [comment]
yes
